apiVersion: v1
kind: Service
metadata:
  name: docker-test-app-service
spec:
  selector:
    app: docker-test-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
